name: Ren'Py Android
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - name: Build APK
        uses: renpy/renpy-android-action@v1
        with:
          project: launcher
          sdk-version: "8.5.3"
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: "*.apk"
